baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Hugo GitHub Issue #8279'

defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true

[languages.en]
weight = 1
languageName = 'English'
languagePrefix = '/news'

[languages.de]
weight = 2
languageName = 'Deutsch'
languagePrefix = '/de/neuigkeiten'

[languages.es]
weight = 3
languageName = 'Espa√±ol'
languagePrefix = '/es/noticias'
